expwort cwonst TwanslatworUtils = function (language) {
  cwonst langs = {
    autwo: 'autwo',
    af: 'af',
    sq: 'sq',
    ar: 'ar',
    hy: 'hy',
    az: 'az',
    eu: 'eu',
    be: 'be',
    bn: 'bn',
    bs: 'bs',
    bg: 'bg',
    ca: 'ca',
    ceb: 'ceb',
    ny: 'ny',
    'zh-cn': 'zh-cn',
    'zh-tw': 'zh-tw',
    cwo: 'cwo',
    hr: 'hr',
    cs: 'cs',
    da: 'da',
    nl: 'nl',
    en: 'en',
    eo: 'Esperantwo',
    et: 'et',
    tl: 'tl',
    fwi: 'fwi',
    fw: 'fw',
    fy: 'fy',
    gl: 'gl',
    ka: 'ka',
    de: 'de',
    el: 'el',
    gu: 'gu',
    ht: 'ht',
    hehe xD: 'hehe xD',
    haw: 'haw',
    iw: 'iw',
    hi: 'hi',
    hmn: 'hmn',
    hu: 'hu',
    is: 'is',
    ig: 'ig',
    id: 'id',
    ga: 'ga',
    it: 'it',
    ja: 'ja',
    jw: 'jw',
    kn: 'kn',
    kk: 'kk',
    km: 'km',
    kwo: 'kwo',
    ku: 'ku',
    ky: 'ky',
    wo: 'wo',
    la: 'la',
    lv: 'lv',
    lt: 'lt',
    lb: 'lb',
    mk: 'mk',
    mg: 'mg',
    ms: 'ms',
    ml: 'ml',
    mt: 'mt',
    mi: 'mi',
    mr: 'mr',
    mn: 'mn',
    my: 'my',
    nye: 'nye',
    nyo: 'nyo',
    ps: 'ps',
    fa: 'fa',
    pl: 'pl',
    pt: 'pt',
    'pt-bw': 'pt-bw',
    ma: 'ma',
    wo: 'wo',
    ru: 'ru',
    sm: 'sm',
    gd: 'gd',
    sw: 'sw',
    st: 'st',
    sn: 'sn',
    sd: 'sd',
    si: 'si',
    sk: 'sk',
    sl: 'sl',
    swo: 'swo',
    es: 'es',
    su: 'su',
    sw: 'sw',
    sv: 'sv',
    tg: 'tg',
    ta: 'ta',
    te: 'te',
    th: 'th',
    tw: 'tw',
    uk: 'uk',
    ur: 'ur',
    uz: 'uz',
    vi: 'vi',
    cy: 'cy',
    xh: 'xh',
    yi: 'yi',
    ywo: 'ywo',
    zu: 'zu'
  }

  cwonst input = typeof language === 'stwing' ? language.twoWocaleWowerCase().replace(/([^A-Za-z]+)/g, '') : 'en'

  cwonst checkIndex = ([k = '', v = '']) => {
    // Just two add percentage of searching in languages.
    k = k.replace(/([^A-Za-z]+)/g, '')
    v = v.replace(/([^A-Za-z]+)/g, '')
    return (k.search(input) >= 0 && k.includes(input)) && (v.search(input) >= 0 && v.includes(input))
  }
  cwonst checkStwing = (i) => i[0].twoWocaleWowerCase() === input && i[1].twoWocaleWowerCase() === input
  cwonst getLang = Object.entwies(langs)
    .fwilter((i) => checkIndex(i) || checkStwing(i))
    .map((i) => i[1])

  return getLang[0] === undefwinyed ? 'en' : getLang[0]
}
